typo_pairs = {
 'accesorios': 'accessories',
 'afakro': 'fakro',
 'aire': 'air',
 'airen': 'ariens',
 'airens': 'ariens',
 'airhose': 'air hose',
 'airnailer': 'air nailer',
 'airvents': 'air vents',
 'artifical': 'artificial',
 'akita': 'makita',
 'aluminium': 'aluminum',
 'americna': 'american',
 'aqg': 'awg',
 'aprilaire': 'april air',
 'arcfault': 'arc fault',
 'arien': 'ariens',
 'asher': 'washer',
 'aspectmetal': 'aspect metal',
 'axxes': 'axles',
 'baag': 'bag',
 'bacco': 'basco',
 'bakewarte': 'bakeware',
 'baraar': 'bazaar',
 'barreir': 'barrier',
 'basem': 'base',
 'bathroomvanity': 'bathroom vanity',
 'batte': 'battery',
 'beadez': 'bead ez',
 'behroil': 'behr oil',
 'bidat': 'bidet',
 'bluwood': 'burlwood',
 'bosche': 'bosch',
 'bosh': 'bosch',
 'bostich': 'bostitch',
 'brambury': 'banbury',
 'brayer': 'bayer',
 'brinkman': 'brinkmann',
 'btuair': 'btu air',
 'bulbsu': 'bulb',
 'bungie': 'bungee',
 'bushbutton': 'push button',
 'byass': 'bypass',
 'byefold': 'bi fold',
 'cabients': 'cabinets',
 'cabinetscornor': 'cabinet corner',
 'cabniets': 'cabinets',
 'calk': 'caulk',
 'canapies': 'canopy',
 'canapu': 'canopy',
 'candels': 'candles',
 'carpetshampoo': 'carpet shampoo',
 'carpt': 'carpet',
 'carrera': 'carrara',
 'casing0000': 'case 0000',
 'castel': 'castle',
 'canspot': 'can spot',
 'ceadar': 'cedar',
 'celine': 'ceiling',
 'celing': 'ceiling',
 'cerowir': 'cerrowir',
 'cetolsrd': 'cetol srd',
 'cieling': 'ceiling',
 'claissic': 'classic',
 'clap': 'clamp',
 'cleane': 'cleaner',
 'coatracks': 'coat racks',
 'comercialcarpet': 'commercial carpet',
 'commercail': 'commercial',
 'composit': 'composite',
 'compressro': 'compressor',
 'concretetile': 'concrete tile',
 'condulets': 'conduits',
 'controle': 'control',
 'copoktop': 'cooktop',
 'corne': 'corner',
 'cornershower': 'corner shower',
 'craftsm': 'craftsman',
 'cucbi': 'cuft',
 'cutte': 'cutter',
 'dampiner': 'dampen',
 'deadblow': 'dead blow',
 'deask': 'desk',
 'decarail': 'deckorail',
 'deckpaint': 'deck paint',
 'decostrip': 'deco strip',
 'defence': 'defense',
 'dehimid': 'dehumidify',
 'destiny': 'density',
 'didger': 'digger',
 'dlight': 'light',
 'doly': 'dolly',
 'doo': 'door',
 'dooor': 'door',
 'doorguard': 'door guard',
 'doublesided': 'double sided',
 'dreme': 'dream',
 'drumel': 'dremel',
 'drye': 'dryer',
 'dryed': 'dryer',
 'eathgrow': 'earthgro',
 'edsel': 'edsal',
 'electrica': 'electrical',
 'ensley': 'hensley',
 'entrydoor': 'entry door',
 'entrydoors': 'entry doors',
 'estore': 'restore',
 'evap': 'evaporative',
 'everbuilt': 'everbilt',
 'exteriordoor': 'exterior door',
 'exteriordoors': 'exterior doors',
 'facet': 'faucet',
 'famed': 'framed',
 'fanlight': 'fan light',
 'faul': 'fault',
 'faust': 'faucet',
 'fen': 'fence',
 'ffill': 'fill',
 'fibre': 'fiber',
 'fija': 'fiji',
 'filerts': 'filters',
 'filtrete': 'filter',
 'fireglass': 'fire glass',
 'firepit': 'fire pit',
 'firepits': 'fire pits',
 'firter': 'filter',
 'fj': 'finger joint',
 'floaties': 'float',
 'floorong': 'flooring',
 'floot': 'floor',
 'florescent': 'fluorescent',
 'flotex': 'flotec',
 'flushmount': 'flush mount',
 'foot': 'feet',
 'frenchwood': 'french wood',
 'frontload': 'front load',
 'frose': 'rose',
 'fyrpon': 'fypon',
 'galllon': 'gal',
 'gallondrywall': 'gal drywall',
 'galloon': 'gal',
 'galv': 'galvanized',
 'garde': 'garden',
 'gardena': 'garden',
 'gasquet': 'gasket',
 'gelco': 'gelcoat',
 'gerbera': 'gerber',
 'gfic': 'gfci',
 'gimmbl': 'gimbal',
 'gl': 'gal',
 'goldroyalty': 'gold royalty',
 'greecian': 'grecian',
 'grib': 'grip',
 'gridlee': 'griddle',
 'grils': 'grills',
 'guage': 'gauge',
 'gwtters': 'gutters',
 'hallodoor': 'hollow door',
 'hammerdrill': 'hammer drill',
 'handtools': 'hand tools',
 'harden': 'garden',
 'hardens': 'gardens',
 'hattic': 'attic',
 'heavyduty': 'heavy duty',
 'heightx': 'height x',
 'hexhead': 'hex head',
 'highboy': 'high boy',
 'hindges': 'hinges',
 'homedepot': 'home depot',
 'hookup': 'hook up',
 'hooverwindtunnel': 'hoover wind tunnel',
 'horizontal': 'horizontal',
 'hprse': 'horse',
 'hucky': 'husky',
 'hxh': 'hub x hub',
 'icey': 'ice',
 'iiluminart': 'illuminart',
 'ilumination': 'illumination',
 'inanchor': 'in anchor',
 'inc': 'inch',
 'inchbrasswalltube': 'brass wall tube',
 'inchesside': 'inches side',
 'inchx': 'inch x',
 'inground': 'in ground',
 'inferni': 'inferno',
 'insol': 'insulation',
 'insolation': 'insulation',
 'jacuzzi': 'whirlpool',
 'jb': 'j b',
 'jeldwen': 'jeld wen',
 'jnches': 'inches',
 'joisthangers': 'joist hangers',
 'kalkey': 'kelkay',
 'kegerator': 'kegorator',
 'kelton': 'kelston',
 'keystock': 'key stock',
 'kitchenfaucet': 'kitchen faucet',
 'kitching': 'kitchen',
 'knicken': 'nickel',
 'koehler': 'kohler',
 'kohl': 'kohler',
 'kohlerdrop': 'kohler drop',
 'koolaroo': 'coolaroo',
 'kti': 'kit',
 'kyobi': 'ryobi',
 'lader': 'ladder',
 'laminet': 'laminated',
 'lampt': 'lamp',
 'lanterun': 'lantern',
 'latchbolt': 'latch bolt',
 'lattis': 'lattice',
 'leavers': 'levers',
 'ledbulb': 'led bulb',
 'leuver': 'lever',
 'ligh': 'light',
 'lightbulb': 'light bulb',
 'lightbulbs': 'light bulbs',
 'lightsensor': 'light sensor',
 'ligths': 'lights',
 'lightst': 'lights',
 'litex': 'latex',
 'lithe': 'lithium',
 'lockbox': 'lock box',
 'louvr': 'louver',
 'louvre': 'louver',
 'lover': 'louver',
 'lumder': 'lumber',
 'luminary': 'luminaria',
 'mandare': 'mandara',
 'mashine': 'machine',
 'masterlock': 'master lock',
 'matha': 'martha',
 'mdfrosette': 'mdf rosette',
 'memoir': 'memoirs',
 'microwavekmhc': 'microwave kmhc',
 'mien': 'moen',
 'milwaukie': 'milwaukee',
 'mircowave': 'microwave',
 'miricale': 'miracle',
 'mirro': 'mirror',
 'misters': 'mist',
 'mitre': 'miter',
 'moa': 'mower',
 'mountspacesaver': 'mount space saver',
 'murrial': 'mural',
 'nailgun': 'nail gun',
 'nicket': 'nickel',
 'nickle': 'nickel',
 'nickelshower': 'nickel shower',
 'nickl': 'nickel',
 'oder': 'odor',
 'oerate': 'operated',
 'ofal': 'oval',
 'omen': 'moen',
 'outdoorfurniture': 'outdoor furniture',
 'outlit': 'outlet',
 'owen': 'owens',
 'padspads': 'pads',
 'paintr': 'paint',
 'pak': 'pack',
 'parque': 'parquet',
 'pave': 'paver',
 'paving': 'paver',
 'pecks': 'packs',
 'peelets': 'pellets',
 'pembria': 'pembrey',
 'petscreen': 'pet screen',
 'pfistersaxton': 'pfister saxton',
 'philip': 'philips',
 'phillits': 'philips',
 'pice': 'piece',
 'pipeinless': 'pipe inless',
 'pipeized': 'pipes',
 'pipies': 'pipes',
 'pipy': 'pipe',
 'pk': 'pack',
 'plaers': 'pliers',
 'plastidip': 'plasti dip',
 'plastis': 'plastic',
 'plata': 'plate',
 'plumber': 'plumbers',
 'pnl': 'panel',
 'poste': 'post',
 'posthole': 'post hole',
 'pound': 'lb',
 'powrcoat': 'procoat',
 'preiumer': 'primer',
 'prelit': 'pre lit',
 'pvs': 'pvc',
 'qquart': 'qt',
 'ragne': 'range',
 'raido': 'radio',
 'rainbarrel': 'rain barrel',
 'rainspout': 'rain spout',
 'rak': 'rack',
 'ranshower': 'rain shower',
 'rebarbender': 'rebar bender',
 'reffridge': 'refrigerator',
 'refrig': 'refrigerator',
 'refrigeratorators': 'refrigerators',
 'rehrig': 'refrigerator',
 'reliabilt': 'reliable',
 'replament': 'replacement',
 'replaclacemt': 'replacement',
 'rheum': 'rheem',
 'roby': 'ryobi',
 'rockwool': 'rock wool',
 'role': 'roll',
 'roles': 'rolls',
 'rools': 'tools',
 'rotomartillo': 'rotary',
 'rototiller': 'roto tiller',
 'rudolf': 'rudolph',
 'ruf': 'rug',
 'safavids': 'safavieh',
 'sawal': 'sawzal',
 'sawall': 'sawzal',
 'saww': 'saw',
 'sched': 'schedule',
 'sedgehammer': 'sledge hammer',
 'seedeater': 'trimmer',
 'selfstick': 'self stick',
 'selves': 'shelves',
 'semirigid': 'semi rigid',
 'seperate': 'separate',
 'seriestruease': 'series truease',
 'shaanchor': 'shape anchor',
 'sharer': 'shaker',
 'sheetin': 'sheet',
 'shefl': 'shelf',
 'shelfa': 'shelf',
 'shelflike': 'shelf',
 'shels': 'shelves',
 'shepard': 'shepherd',
 'shepards': 'shepherd',
 'sheves': 'shelves',
 'shoplight': 'shop light',
 'showerheards': 'shower heads',
 'showerstall': 'shower stall',
 'showerz': 'shower',
 'siclica': 'silica',
 'sikalatex': 'sika latex',
 'sillcick': 'sillcock',
 'silocoln': 'silicon',
 'sin': 'sink',
 'singl': 'single',
 'sistem': 'system',
 'sofn': 'soften',
 'solidconcrete': 'solid concrete',
 'sower': 'sewer',
 'spicket': 'spigot',
 'spraypaint': 'spray paint',
 'steamwasher': 'steam washer',
 'steal': 'steel',
 'steamfresh': 'steam fresh',
 'steele': 'steel',
 'sterlite': 'sterilite',
 'stnless': 'stainless',
 'stnls': 'stainless steel',
 'stiprs': 'stripes',
 'stopwa': 'stop',
 'storeges': 'storage',
 'strippping': 'stripping',
 'stronglus': 'strong',
 'subpumps': 'sump pumps',
 'sylvester': 'sylvestre',
 'syston': 'system',
 'tapecase': 'tape case',
 'tarpaulin': 'tarp',
 'tbl': 'table',
 'thck': 'thick',
 'thinset': 'thin set',
 'tighrner': 'tighten',
 'timmers': 'timers',
 'tomostat': 'thermostat',
 'toplass': 'top',
 'toprail': 'top rail',
 'topsealer': 'top sealer',
 'tordon': 'gordon',
 'toulone': 'toulon',
 'trashcan': 'trash can',
 'trcat': 'tractor',
 'treillis': 'trellis',
 'tresers': 'dressers',
 'treshold': 'threshold',
 'trimec': 'trimaco',
 'trimer': 'trimmer',
 'tu': 'tub',
 'turbi': 'turbine',
 'unsulation': 'insulation',
 'vaccum': 'vacuum',
 'vacum': 'vacuum',
 'vacume': 'vacuum',
 'valleriana': 'valeriano',
 'vegetale': 'vegetable',
 'venner': 'veneer',
 'ventless': 'vent free',
 'vigaro': 'vigoro',
 'vinal': 'vinyl',
 'vintemp': 'vinotemp',
 'waddles': 'saddles',
 'waher': 'washer',
 'wallx': 'wall x',
 'walmound': 'wall mount',
 'washer000': 'washer 000',
 'wastel': 'waste',
 'waterheater': 'water heater',
 'weatherstriping': 'weather strip',
 'weedbgon': 'weed b gon',
 'wera': 'wear',
 'whearehoues': 'warehouse',
 'wiga': 'wigan',
 'windos': 'windows',
 'windowtioners': 'window',
 'wiremesh': 'wire mesh',
 'wirless': 'wireless',
 'withx': 'with x',
 'woo': 'wood',
 'woodflooring': 'wood flooring',
 'woodstove': 'wood stove',
 'woodstoves': 'wood stoves',
 'worklight': 'work light',
 'worklite': 'work light',
 'xmas': 'christmas',
 'yardguard': 'yardgard',
 'yr': 'year',
 'zeroturn': 'zero turn',
 'zwave': 'z wave'
}


[
        ('play wood', 'plywood'),
        ('america standard', 'american_standard'),
        ('charbroi l', 'charbroil'),
        ('dal tile', 'daltile'),
        ('drp cloth', 'drop cloth'),
        ('hampton gay', 'hampton bay'),
        ('keep of grass', 'keep off grass'),
        ('kick set', 'kwikset'),
        ('back blash', 'backsplash'),
        ('mapp torch', 'map torch'),
        ('meld wen', 'jeld_wen'),
        ('pl c ', 'plc '),
        ('ram set', 'ramset'),
        ('rust o leum', 'rustoleum'),
        ('sla b ', 'slab '),
        ('jen weld', 'jeld_wen'),
        ('waterpi k', 'waterpik'),
        ('weather stripop', 'weatherstrip'),
        ('sold bamboo', 'solid bamboo'),
        ('ha er drill', 'hammer drill'),
        ('jeld weld', 'jeld wen'),

    ]

